dual test v1

diff --git a/.github/workflows/medallion_v2_solo.yml b/.github/workflows/medallion_v2_solo.yml
--- a/.github/workflows/medallion_v2_solo.yml
+++ b/.github/workflows/medallion_v2_solo.yml
@@ -33,6 +33,7 @@ jobs:
 
 #Load data to Bronze
 
+
       - name: Create "Load data to Bronze" Interactive Job
         id: create_load_data
         run: |
@@ -50,7 +51,6 @@ jobs:
           echo "groupId=$(echo "$GROUP_ID" | jq -r '.groupId' )" >> $GITHUB_OUTPUT
 
       - name: Group state check
-        id: check_group_status
         run: |
           while true; do
             response=$(curl -X GET "http://localhost:9888/api/v1/group/name/$JOB_1_NAME" \
@@ -84,7 +84,54 @@ jobs:
 
 #Bronze to Silver
           
+      - name: Create "Bronze to Silver" Interactive Job
+        id: create_bronze_silver
+        run: |
+          GROUP_ID=$(curl -X POST "http://localhost:9888/api/v1/group" \
+          -H "Accept: application/json" \
+          -H "Content-Type: multipart/form-data" \
+          -F "name=$JOB_2_NAME" \
+          -F "clusterName=default" \
+          -F "kind=job" \
+          -F "language=python" \
+          -F "scale=1" \
+          -F "pyRequirements=pandas" \
+          -F "pyFiles=@/runner/_work/Medallion/Medallion/Jobs/bronze_to_silver.py") \
+          --form-string 'jobConfig=spark.jars.packages=io.delta:delta-core_2.12:2.4.0;spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension;spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog'
+          echo $GROUP_ID
+          echo "groupId=$(echo "$GROUP_ID" | jq -r '.groupId' )" >> $GITHUB_OUTPUT
+
+      - name: Group state check
+        run: |
+          while true; do
+            response=$(curl -X GET "http://localhost:9888/api/v1/group/name/$JOB_2_NAME" \
+              -H "Accept: application/json")
+
+            STATE=$(jq -r '.jobs[].state' <<< "$response")
+            if [[ $STATE = READY ]]; then
+              echo "Group is ready!"
+              break
+            fi
           
+            echo "Group is not ready. Wait..."
+            sleep 15 
+          done
+
+      - name: Execute "Bronze to Silver" Job
+        run: |
+          response=$(curl -X POST "http://localhost:9888/api/v1/group/${{ steps.create_bronze_silver.outputs.groupId }}/job/execute" \
+          -H "Accept: application/json" \
+          -H "Content-Type: application/json" \
+          -d '{"type":"interactive_job_execute","jobClass":"bronze_to_silver.BronzeToSilver","jobConfig":{"animals_bronze_path":"s3a://ilum-files/tables/bronze/animals.csv","owners_bronze_path":"s3a://ilum-files/tables/bronze/owners.csv","species_bronze_path":"s3a://ilum-files/tables/bronze/species.csv","animals_silver_path":"s3a://ilum-files/tables/silver/animals_delta","owners_silver_path":"s3a://ilum-files/tables/silver/owners_delta"}}')
+          
+          RESULT=$(jq -r '.result' <<< "$response")
+          
+          if [[ "$RESULT" == "Processing data from bronze to silver complete!" ]]; then
+            echo "$RESULT"
+          else
+            echo "echo "Data load failed! Result: $result""
+            exit 1
+          fi    
           
           
           
