all test v1

diff --git a/.github/workflows/medallion_v2_solo.yml b/.github/workflows/medallion_v2_solo.yml
--- a/.github/workflows/medallion_v2_solo.yml
+++ b/.github/workflows/medallion_v2_solo.yml
@@ -93,7 +93,7 @@ jobs:
           -H "Accept: application/json"
 
     #Bronze to Silver
-        #-F "jobConfig=spark.jars.packages=io.delta:delta-core_2.12:2.4.0;spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension;spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" \
+
       - name: Create "Bronze to Silver" Interactive Job
         id: create_bronze_silver
         run: |
@@ -157,9 +157,73 @@ jobs:
           curl -X DELETE "http://localhost:9888/api/v1/group/${{ steps.create_bronze_silver.outputs.groupId }}" \
           -H "Accept: application/json"
           
+#Silver to Gold
+
+      - name: Create "Silver to Gold" Interactive Job
+        id: create_silver_gold
+        run: |
+          GROUP_3_ID=$(curl -X POST "http://localhost:9888/api/v1/group" \
+          -H "Accept: application/json" \
+          -H "Content-Type: multipart/form-data" \
+          -F "name=$JOB_3_NAME" \
+          -F "clusterName=default" \
+          -F "kind=job" \
+          -F "language=python" \
+          -F "scale=1" \
+          -F "pyRequirements=pandas" \
+          --form-string "jobConfig=spark.jars.packages=io.delta:delta-core_2.12:2.4.0;spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension;spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" \
+          -F "pyFiles=@/runner/_work/Medallion/Medallion/Jobs/silver_to_gold.py")
+          echo $GROUP_3_ID
+          echo "groupId=$(echo "$GROUP_3_ID" | jq -r '.groupId' )" >> $GITHUB_OUTPUT
+
+      - name: Group state check
+        run: |
+          while true; do
+            response=$(curl -X GET "http://localhost:9888/api/v1/group/name/$JOB_3_NAME" \
+              -H "Accept: application/json")
           
+            STATE=$(jq -r '.jobs[].state' <<< "$response")
+            if [[ $STATE = READY ]]; then
+              echo "Group is ready!"
+              break
+            fi
           
+            echo "Group is not ready. Wait..."
+            sleep 20
+          done
+
+      - name: Execute "Silver to Gold" Job
+        run: |
+          response=$(curl -X POST "http://localhost:9888/api/v1/group/${{ steps.create_silver_gold.outputs.groupId }}/job/execute" \
+          -H "Accept: application/json" \
+          -H "Content-Type: application/json" \
+          -d '{"type":"interactive_job_execute","jobClass":"silver_to_gold.SilverToGold","jobConfig":{"animals_silver_path":"s3a://ilum-files/tables/silver/animals_delta","owners_silver_path":"s3a://ilum-files/tables/silver/owners_delta","animals_gold_path":"s3a://ilum-files/tables/gold/animals_delta","owners_gold_path":"s3a://ilum-files/tables/gold/owners_delta"}}')
           
+          echo $response
+          
+          RESULT=$(jq -r '.result' <<< "$response")
+          
+          echo $RESULT
+          
+          if [[ "$RESULT" == "Processing data from silver to gold complete!" ]]; then
+            echo "$RESULT"
+          else
+            echo "echo "Data load failed! Response: $response""
+            exit 1
+          fi    
+
+      - name: Stop "Silver to Gold" group
+        run: |
+          curl -X POST "http://localhost:9888/api/v1/group/${{ steps.create_silver_gold.outputs.groupId }}/stop" \
+          -H "Accept: application/json"
+
+      - name: Delete "Silver to Gold" group
+        run: |
+          curl -X DELETE "http://localhost:9888/api/v1/group/${{ steps.create_silver_gold.outputs.groupId }}" \
+          -H "Accept: application/json"
+          
+      - name: Medallion processing complete
+        run: echo "Medallion processing complete!"
           
           
           
